In [1]:
# Constants
import config.execution_parameters
from config.execution_parameters import *

# Project libraries
from src.simulator_package.simulator_functions import *
import src.hmm_package.generate_hmm
from src.hmm_package.generate_hmm import *
from src.plot_and_print_info.plots_and_print_info import *

import random
import importlib

In [43]:
importlib.reload(src.hmm_package.generate_hmm)
from src.hmm_package.generate_hmm import *
importlib.reload(config.execution_parameters)
from config.execution_parameters import *

In [44]:
# We want to fit the model over a pool of empty users, with a certain conversion rate to mimic external factors
empty_users = 10000
adstock_only_empty = tf.zeros([empty_users, N_states, execution_duration+1], dtype=float)
output_only_empty = np.zeros([empty_users, execution_duration+1])

# Lets add a 3% of conversion due to external factors
for temp in range(round(0.03*empty_users)):
    output_only_empty[temp, random.randint(1,execution_duration+1):] = 1

In [47]:
model = build_hmm_to_fit_mu(states_observable=STATES_ARE_OBSERVABLE)

compiler = CompilerInfoMu(LR_EXPONENTIAL_DECAY)
model.compile(
    loss = compiler.loss,
    optimizer = compiler.optimizer,
    run_eagerly = True
)

fit_model(model, adstock_only_empty, output_only_empty)

Epoch 1/10000
40/40 [==============================] - 13s 316ms/step - loss: 0.0576
Epoch 2/10000
40/40 [==============================] - 13s 322ms/step - loss: 0.0571
Epoch 3/10000
40/40 [==============================] - 12s 305ms/step - loss: 0.0566
Epoch 4/10000
40/40 [==============================] - 13s 327ms/step - loss: 0.0561
Epoch 5/10000
40/40 [==============================] - 12s 306ms/step - loss: 0.0556
Epoch 6/10000
40/40 [==============================] - 13s 317ms/step - loss: 0.0552
Epoch 7/10000
40/40 [==============================] - 12s 303ms/step - loss: 0.0547
Epoch 8/10000
40/40 [==============================] - 12s 303ms/step - loss: 0.0543
Epoch 9/10000
40/40 [==============================] - 12s 303ms/step - loss: 0.0539
Epoch 10/10000
40/40 [==============================] - 12s 301ms/step - loss: 0.0534
Epoch 11/10000
40/40 [==============================] - 12s 302ms/step - loss: 0.0530
Epoch 12/10000
40/40 [==============================] - 12s 303

KeyboardInterrupt: 

In [56]:
make_non_exposed_user_transtion_matrix([ -2.7419195, -7.4647417, -1.1010361, -5.92728  ],adstock_only_empty[0:1])

<tf.Tensor: shape=(1, 30, 3, 3), dtype=float32, numpy=
array([[[[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01, 1.9965090e-03],
         [1.0000000e-06, 1.0000000e-06, 9.9999797e-01]],

        [[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01, 1.9965090e-03],
         [1.0000000e-06, 1.0000000e-06, 9.9999797e-01]],

        [[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01, 1.9965090e-03],
         [1.0000000e-06, 1.0000000e-06, 9.9999797e-01]],

        [[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01, 1.9965090e-03],
         [1.0000000e-06, 1.0000000e-06, 9.9999797e-01]],

        [[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01, 1.9965090e-03],
         [1.0000000e-06, 1.0000000e-06, 9.9999797e-01]],

        [[9.3895000e-01, 6.0512062e-02, 5.3795549e-04],
         [2.4904761e-01, 7.4895585e-01,

In [50]:
model.weights

[<tf.Variable 'transition_prob_layer_mu_10/mu:0' shape=(4,) dtype=float32, numpy=array([ 4.7419195, -4.4647417, -1.1010361, -8.92728  ], dtype=float32)>]

In [57]:
a = make_non_exposed_user_transtion_matrix([ -2.7419195, -7.4647417, -1.1010361, -5.92728  ],adstock_only_empty[0:1])
np.linalg.matrix_power( a.numpy(), 31 )

array([[[[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05, 9.9993801e-01]],

        [[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05, 9.9993801e-01]],

        [[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05, 9.9993801e-01]],

        [[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05, 9.9993801e-01]],

        [[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05, 9.9993801e-01]],

        [[7.8571308e-01, 1.9000936e-01, 2.4277475e-02],
         [7.8201544e-01, 1.8912701e-01, 2.8857099e-02],
         [4.7289406e-05, 1.3871699e-05