In [1]:
# Constants
from config.execution_parameters import *

# Project libraries
from src.simulator_package.simulator_functions import *
import src.hmm_package.generate_hmm
from src.hmm_package.generate_hmm import *
from src.plot_and_print_info.plots_and_print_info import *

import importlib

In [2]:
importlib.reload(src.hmm_package.generate_hmm)
from src.hmm_package.generate_hmm import *

In [3]:
advertising_campaign = SimulationClass(ANALYSIS_MODE)
advertising_campaign.simulate()

adstock = compute_adstock(observation=advertising_campaign.results["user_expositions"])
output = np.append( np.zeros([adstock.shape[0], 1]), advertising_campaign.results["user_outcome"], axis=1 )

2022-02-22 18:24:57.188841: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
    adstock.shape

TensorShape([12860, 3, 31])

In [5]:
empty_users = 8000
adstock_with_empty = tf.concat([adstock, tf.zeros([empty_users, adstock.shape[1], adstock.shape[2]], dtype=float)], axis = 0)
output_with_empty = np.append(output, np.zeros([empty_users, adstock.shape[2]]), axis = 0)

In [30]:
adstock_with_empty = tf.zeros([2000, adstock.shape[1], adstock.shape[2]], dtype=float)
output_with_empty = np.zeros([2000, adstock.shape[2]])

In [31]:
model = build_hmm_to_fit( states_observable=STATES_ARE_OBSERVABLE )

compiler = CompilerInfo(LR_EXPONENTIAL_DECAY)
model.compile(
    loss = compiler.loss,
    optimizer = compiler.optimizer,
    run_eagerly = True
)

fit_model(model, adstock_with_empty, output_with_empty)

Epoch 1/100
8/8 [==============================] - 23s 3s/step - loss: 3048.9768
Epoch 2/100
8/8 [==============================] - 22s 3s/step - loss: 2955.5283
Epoch 3/100
8/8 [==============================] - 21s 3s/step - loss: 2932.1565
Epoch 4/100
8/8 [==============================] - 24s 3s/step - loss: 2908.9656
Epoch 5/100
8/8 [==============================] - 27s 3s/step - loss: 2885.9661
Epoch 6/100
3/8 [==========>...................] - ETA: 18s - loss: 2926.8997

KeyboardInterrupt: 

In [ ]:
fit_model(model, adstock_with_empty, output_with_empty)

Epoch 1/100
8/8 [==============================] - 23s 3s/step - loss: 2784.8716
Epoch 2/100
8/8 [==============================] - 21s 3s/step - loss: 2763.0315
Epoch 3/100
8/8 [==============================] - 21s 3s/step - loss: 2741.4041
Epoch 4/100
8/8 [==============================] - 20s 3s/step - loss: 2719.9846
Epoch 5/100
8/8 [==============================] - 20s 3s/step - loss: 2698.7717
Epoch 6/100
8/8 [==============================] - 21s 3s/step - loss: 2677.7610
Epoch 7/100
8/8 [==============================] - 20s 3s/step - loss: 2656.9536
Epoch 8/100
8/8 [==============================] - 20s 2s/step - loss: 2636.3462
Epoch 9/100
8/8 [==============================] - 20s 3s/step - loss: 2615.9375
Epoch 10/100
8/8 [==============================] - 20s 2s/step - loss: 2595.7258
Epoch 11/100
8/8 [==============================] - 21s 3s/step - loss: 2575.7090
Epoch 12/100
8/8 [==============================] - 20s 3s/step - loss: 2555.8848
Epoch 13/100
8/8 [=======

In [35]:
model.weights

[<tf.Variable 'transition_prob_layer_2/mu:0' shape=(4,) dtype=float32, numpy=array([-0.        ,  0.06619387,  0.26603213,  0.27003407], dtype=float32)>,
 <tf.Variable 'transition_prob_layer_2/beta:0' shape=(12,) dtype=float32, numpy=
 array([-0.1619116 , -0.2684288 , -0.2631067 ,  0.04105067,  0.14844477,
        -0.37556982,  0.17426813, -0.20132601, -0.03317034, -0.29804862,
        -0.28567052,  0.00739706], dtype=float32)>]

In [37]:
make_transition_matrix(-model.weights[0], model.weights[1], adstock_with_empty[0:1,:,:])

<tf.Tensor: shape=(1, 30, 3, 3), dtype=float32, numpy=
array([[[[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01, 3.0174839e-01],
         [1.0000000e-10, 1.0000000e-10, 1.0000000e+00]],

        [[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01, 3.0174839e-01],
         [1.0000000e-10, 1.0000000e-10, 1.0000000e+00]],

        [[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01, 3.0174839e-01],
         [1.0000000e-10, 1.0000000e-10, 1.0000000e+00]],

        [[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01, 3.0174839e-01],
         [1.0000000e-10, 1.0000000e-10, 1.0000000e+00]],

        [[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01, 3.0174839e-01],
         [1.0000000e-10, 1.0000000e-10, 1.0000000e+00]],

        [[3.4060526e-01, 3.4060535e-01, 3.1878936e-01],
         [3.0295843e-01, 3.9529318e-01,

In [27]:
a = make_transition_matrix(-model.weights[0], model.weights[1], tf.zeros([1, adstock.shape[1], adstock.shape[2]]))
np.linalg.matrix_power( a[0,0,:].numpy(), 30 )

array([[3.2995809e-02, 3.2995809e-02, 9.3400830e-01],
       [3.1312186e-02, 3.1312186e-02, 9.3737555e-01],
       [1.0704581e-09, 1.0704581e-09, 1.0000000e+00]], dtype=float32)

In [38]:
output_with_empty

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])